## [특강] Numpy, Pandas, Matplotlib

### 1. Numpy: 고속 연산, 슬라이싱 및 차원 제어
#### 1.1 명시적 타입 배열 생성과 다차원 슬라이싱

배열
- 메모리상에 연속된 구조, 인덱스 연산자([]) 접근 가능
- 동일한 자료형으로 데이터가 구성
- C언어로 개발(직접 메모리 접근)
- dtype: 자료형 명시(예 = np.int64, np.float64)

In [ ]:
import numpy as np

nums = np.array(([10, 20, 30]), dtype = np.float64)#1차원 배열(Vector), float써서 .붙임
nums

array([10., 20., 30.])

In [ ]:
nums[2] #int64고 8bit씩 이동해 다른 값으로 이동, 위치를 고려해 같은 자료형에만 이용
#"같은 자료형" -> 1차원 배열(선)

np.int64(30)

In [ ]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
    ]) #2차원 배열(Matrix)

matrix
#3차원 이상의 배열은 Tensor라고 한다.

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

#### 배열 선택, 슬라이싱
- matrix[행, 열]
- matrix[0:2, 1:3] : 행은 0, 1, 열은 1, 2
- matrix[:, 0] -> 모든 행의 0 번째 열
- matrix[1:, :2] -> 행은 1번 인덱스 부터 전체, 열은 1번 인덱스 이하

In [16]:
print("0행 2열:", matrix[0][2], matrix[0,2]) #두 표기방식 다 사용 가능
print(matrix[0:2, 1:3])
print(matrix[:,0])
print(matrix[1:,:2])

0행 2열: 30 30
[[20 30]
 [50 60]]
[10 40 70]
[[40 50]
 [70 80]]


#### 1.2 차원 변경(reshape, flatten)과 축(Axis)

reshape(행, 열) / flatten()

In [ ]:
- reshape(1.행, 2.열) - 1차원 배열 -> 지정된 행과 열 구조로 차원수를 변경, -1: 자동 결정
- arange(1.시작, 2.종료, 3.증감단위) -> 시작 이상 종료 미만으로 숫자를 생성
- flatten() - 2차원 배결 -> 1차원으로 평탄화

In [25]:
arr = np.arange(1, 13)
arr

#mat_3x4 = arr.reshape(3, 4)
#mat_3x4 = arr.reshape(3, -1)
mat_3x4 = arr.reshape(-1, 4)
print(mat_3x4)

flat_arr = mat_3x4.flatten()
print(flat_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


축(axis)

2차원 배열에서 연산의 방향을 설정
- axis: 0 -> 행기준에서 연산
- axis: 1 -> 열기준에서 연산

In [35]:
mat = np.arange(1, 7).reshape(2, -1)
print(mat)
sum_axis0 = mat.sum(axis=0)
sum_axis1 = mat.sum(axis=1)

print("행 기준 합계:", sum_axis0)
print("열 기준 합계:", sum_axis1)


[[1 2 3]
 [4 5 6]]
행 기준 합계: [5 7 9]
열 기준 합계: [ 6 15]


#### 1.3 Numpy 브로드캐스팅(Broadcasting) 연산

In [38]:
mat = np.array([
    [10, 20, 30],
    [40, 50, 60]
    ])

print(mat * 5)
print(mat + 5)

[[ 50 100 150]
 [200 250 300]]
[[15 25 35]
 [45 55 65]]


In [39]:
vec = np.array([1,2,3])

mat + vec

array([[11, 22, 33],
       [41, 52, 63]])

#### 1.4 행렬 전치(Transpose) 및 행렬곱(@)

- 객체.transpose() -> {행, 열} -> {열, 행} /전치
    - 객체.T
- 행렬 곱 연산(@)

In [47]:
mat = np.array([
    [1,2,3],
    [4,5,6]
])

print(mat)
print("전치 행렬:\n", mat.transpose())
print("전치 행렬:\n", mat.T)

[[1 2 3]
 [4 5 6]]
전치 행렬:
 [[1 4]
 [2 5]
 [3 6]]
전치 행렬:
 [[1 4]
 [2 5]
 [3 6]]


In [51]:
mat1 = np.array([[10, 20], [30, 40]])
mat2 = np.array([[1,2],[4,5]])
mat3 = mat1 @ mat2

print(mat1)
print(mat2)
print(mat3)

[[10 20]
 [30 40]]
[[1 2]
 [4 5]]
[[ 90 120]
 [190 260]]
